# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Diagrammer.

Build with:
    pyinstaller diagrammer.spec

Produces a one-folder distribution in dist/Diagrammer/.
On macOS it creates a .app bundle in dist/Diagrammer.app.
"""

import sys
from pathlib import Path

block_cipher = None

# ── Paths ──────────────────────────────────────────────────────────────
HERE = Path(SPECPATH)
SRC = HERE / "src"
PKG = SRC / "diagrammer"

# ── Platform helpers ───────────────────────────────────────────────────
IS_MAC = sys.platform == "darwin"
IS_WIN = sys.platform == "win32"

# macOS .icns lives in misc/; Windows .ico is generated by CI from PNGs.
MAC_ICON = str(HERE / "misc" / "diagrammer2_icon.icns") if IS_MAC else None
WIN_ICO = HERE / "diagrammer.ico"
WIN_ICON = str(WIN_ICO) if IS_WIN and WIN_ICO.exists() else None

# ── Qt modules to EXCLUDE (not used by Diagrammer) ────────────────────
# Diagrammer uses only: QtCore, QtGui, QtWidgets, QtSvg, QtPrintSupport
EXCLUDE_QT = [
    "PySide6.Qt3DAnimation",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DExtras",
    "PySide6.Qt3DInput",
    "PySide6.Qt3DLogic",
    "PySide6.Qt3DRender",
    "PySide6.QtBluetooth",
    "PySide6.QtCharts",
    "PySide6.QtConcurrent",
    "PySide6.QtDataVisualization",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
    "PySide6.QtHttpServer",
    "PySide6.QtLocation",
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtNetwork",
    "PySide6.QtNetworkAuth",
    "PySide6.QtNfc",
    "PySide6.QtOpenGL",
    "PySide6.QtOpenGLWidgets",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
    "PySide6.QtPositioning",
    "PySide6.QtQml",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.QtQuickControls2",
    "PySide6.QtQuickWidgets",
    "PySide6.QtRemoteObjects",
    "PySide6.QtScxml",
    "PySide6.QtSensors",
    "PySide6.QtSerialBus",
    "PySide6.QtSerialPort",
    "PySide6.QtSpatialAudio",
    "PySide6.QtSql",
    "PySide6.QtStateMachine",
    "PySide6.QtTest",
    "PySide6.QtTextToSpeech",
    "PySide6.QtUiTools",
    "PySide6.QtWebChannel",
    "PySide6.QtWebEngine",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebSockets",
    "PySide6.QtXml",
]

# Other large modules we don't need
EXCLUDE_MISC = [
    "tkinter",
    "unittest",
    "xmlrpc",
    "pydoc",
]

EXCLUDES = EXCLUDE_QT + EXCLUDE_MISC

# ── Bundled data ───────────────────────────────────────────────────────
# Package data that setuptools would install but PyInstaller won't find
# automatically.  Each tuple is (source_glob, dest_folder_in_bundle).
datas = [
    (str(PKG / "components"), "diagrammer/components"),
    (str(PKG / "icons"), "diagrammer/icons"),
    (str(PKG / "docs"), "diagrammer/docs"),
    (str(PKG / "fonts"), "diagrammer/fonts"),
    (str(PKG / "defaults.yaml"), "diagrammer"),
]

# ── Analysis ───────────────────────────────────────────────────────────
a = Analysis(
    [str(PKG / "__main__.py")],
    pathex=[str(SRC)],
    binaries=[],
    datas=datas,
    hiddenimports=[
        # matplotlib backends needed for LaTeX rendering
        "matplotlib.backends.backend_agg",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=EXCLUDES,
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, cipher=block_cipher)

# ── Executable ─────────────────────────────────────────────────────────
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Diagrammer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # GUI app, no terminal window
    icon=WIN_ICON if IS_WIN else MAC_ICON,
)

# ── Collect into folder ───────────────────────────────────────────────
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Diagrammer",
)

# ── macOS .app bundle ─────────────────────────────────────────────────
if IS_MAC:
    app = BUNDLE(
        coll,
        name="Diagrammer.app",
        icon=MAC_ICON,
        bundle_identifier="com.diagrammer.app",
        info_plist={
            "CFBundleDisplayName": "Diagrammer",
            "CFBundleShortVersionString": "0.1.0",
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "12.0",
        },
    )
