# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Diagrammer.

Build with:
    pyinstaller diagrammer.spec

Produces a one-folder distribution in dist/Diagrammer/.
On macOS it creates a .app bundle in dist/Diagrammer.app.
"""

import re
import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

# ── Paths ──────────────────────────────────────────────────────────────
HERE = Path(SPECPATH)
SRC = HERE / "src"
PKG = SRC / "diagrammer"

# Single source of truth for the version: src/diagrammer/__init__.py.
# Parsed via regex (not imported) so we don't pull PySide6/matplotlib
# into PyInstaller's spec-evaluation environment.
_init_text = (PKG / "__init__.py").read_text(encoding="utf-8")
_match = re.search(r'^__version__\s*=\s*[\'"]([^\'"]+)[\'"]', _init_text, re.M)
if not _match:
    raise RuntimeError("Could not find __version__ in src/diagrammer/__init__.py")
APP_VERSION = _match.group(1)

# ── Platform helpers ───────────────────────────────────────────────────
IS_MAC = sys.platform == "darwin"
IS_WIN = sys.platform == "win32"

# macOS .icns lives in misc/; Windows .ico is generated by CI from PNGs.
MAC_ICON = str(HERE / "misc" / "diagrammer2_icon.icns") if IS_MAC else None
WIN_ICO = HERE / "diagrammer.ico"
WIN_ICON = str(WIN_ICO) if IS_WIN and WIN_ICO.exists() else None

# ── Qt modules to EXCLUDE (not used by Diagrammer) ────────────────────
# Diagrammer uses only: QtCore, QtGui, QtWidgets, QtSvg, QtPrintSupport
EXCLUDE_QT = [
    "PySide6.Qt3DAnimation",
    "PySide6.Qt3DCore",
    "PySide6.Qt3DExtras",
    "PySide6.Qt3DInput",
    "PySide6.Qt3DLogic",
    "PySide6.Qt3DRender",
    "PySide6.QtBluetooth",
    "PySide6.QtCharts",
    "PySide6.QtConcurrent",
    "PySide6.QtDataVisualization",
    "PySide6.QtDesigner",
    "PySide6.QtHelp",
    "PySide6.QtHttpServer",
    "PySide6.QtLocation",
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtNetwork",
    "PySide6.QtNetworkAuth",
    "PySide6.QtNfc",
    "PySide6.QtOpenGL",
    "PySide6.QtOpenGLWidgets",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
    "PySide6.QtPositioning",
    "PySide6.QtQml",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.QtQuickControls2",
    "PySide6.QtQuickWidgets",
    "PySide6.QtRemoteObjects",
    "PySide6.QtScxml",
    "PySide6.QtSensors",
    "PySide6.QtSerialBus",
    "PySide6.QtSerialPort",
    "PySide6.QtSpatialAudio",
    "PySide6.QtSql",
    "PySide6.QtStateMachine",
    "PySide6.QtTest",
    "PySide6.QtTextToSpeech",
    "PySide6.QtUiTools",
    "PySide6.QtWebChannel",
    "PySide6.QtWebEngine",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineQuick",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebSockets",
    "PySide6.QtXml",
]

# Other large modules we don't need. IMPORTANT: do not exclude stdlib
# modules that third-party packages might import at regular import time
# (e.g. ``unittest.mock``, ``xmlrpc.client``). matplotlib in particular
# pulls ``unittest`` in via its dependency chain and will fail to import
# in the frozen app with ``No module named 'unittest'`` if we strip it.
# ``tkinter`` is safe to drop because matplotlib only touches it from
# its TkAgg backend, which we don't bundle.
EXCLUDE_MISC = [
    "tkinter",
    # Stdlib modules nothing in our dependency tree imports at load
    # time. ``unittest`` MUST stay (matplotlib uses ``unittest.mock``
    # via its dependency chain), but ``xmlrpc`` and ``pydoc`` are pure
    # collateral and reclaim ~2 MB.
    "xmlrpc",
    "pydoc",
    "pydoc_data",
]

EXCLUDES = EXCLUDE_QT + EXCLUDE_MISC

# ── Bundled data ───────────────────────────────────────────────────────
# Package data that setuptools would install but PyInstaller won't find
# automatically.  Each tuple is (source_glob, dest_folder_in_bundle).
datas = [
    (str(PKG / "components"), "diagrammer/components"),
    (str(PKG / "icons"), "diagrammer/icons"),
    (str(PKG / "docs"), "diagrammer/docs"),
    (str(PKG / "fonts"), "diagrammer/fonts"),
    (str(PKG / "defaults.yaml"), "diagrammer"),
    (str(PKG / "examples"), "diagrammer/examples"),
    # tutorial.md lives at the repo-root docs/ folder (not inside the
    # package). HelpWindow looks for it under ``diagrammer/docs/`` at
    # runtime, so bundle it into the same destination as the package
    # docs. Without this, the frozen app shows "Document not found:
    # tutorial.md" when the user picks Help → Tutorial.
    (str(HERE / "docs" / "tutorial.md"), "diagrammer/docs"),
]

# ziamath / ziafont ship MathML schema files, font metrics, and bundled
# fonts (STIX Two Math, etc.) inside their package directories. Without
# pulling those data files in explicitly PyInstaller would only freeze
# the .py modules and ziamath would fail at import or render time
# looking for missing resources.
datas += collect_data_files("ziamath")
datas += collect_data_files("ziafont")
datas += collect_data_files("latex2mathml")

# ── Analysis ───────────────────────────────────────────────────────────
a = Analysis(
    [str(PKG / "__main__.py")],
    pathex=[str(SRC)],
    binaries=[],
    datas=datas,
    hiddenimports=[
        # matplotlib backends needed for LaTeX rendering.
        #
        # Since PyInstaller 5.0 the matplotlib hook no longer auto-
        # collects every backend; it only bundles backends referenced
        # via a literal ``matplotlib.use("...")`` call or explicit
        # import. Our annotation math pipeline calls
        # ``fig.savefig(buf, format="svg")``, which lazily imports
        # ``matplotlib.backends.backend_svg`` via ``importlib``. Without
        # listing it here, the import fails at runtime in the frozen
        # app and both inline ($...$) and display ($$...$$) math
        # render as nothing. See pyinstaller/pyinstaller#6760.
        #
        # backend_pdf / backend_ps are included because matplotlib's
        # ``text.usetex`` pipeline shells out to latex + dvips/dvipng
        # and can pull those backends in for PostScript/PDF
        # post-processing.
        "matplotlib.backends.backend_agg",
        "matplotlib.backends.backend_svg",
        "matplotlib.backends.backend_pdf",
        "matplotlib.backends.backend_ps",
        # ziamath is imported lazily inside _render_with_ziamath()
        # in annotation_item.py via a top-level ``import ziamath``
        # statement nested in a function. PyInstaller's static
        # analyzer normally catches these, but we list it (and its
        # transitive deps) explicitly so the frozen app definitely
        # has the display-math renderer available without needing
        # a system LaTeX install.
        "ziamath",
        "ziafont",
        "latex2mathml",
    ] + collect_submodules("ziamath") + collect_submodules("ziafont"),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=EXCLUDES,
    noarchive=False,
    cipher=block_cipher,
)


# ── Strip unused matplotlib data ─────────────────────────────────────
# matplotlib's mpl-data ships ~9 MB of resources, much of which we
# never touch because Diagrammer only renders SVG via the agg backend
# and never opens an interactive figure window.
#
#   * sample_data/   — PNG/CSV examples for matplotlib's own gallery
#   * fonts/afm/     — Adobe Font Metrics, only used by the PS backend
#   * fonts/pdfcorefonts/ — only used by the PDF backend's "core fonts"
#                          mode; our usetex path never invokes it
#   * images/        — toolbar icons for the interactive figure window
#
# fonts/ttf/ MUST stay (mathtext fontsets cm/stix/dejavusans live
# there and the settings dialog lets users switch between them).
_MPL_STRIP_PREFIXES = (
    "matplotlib/mpl-data/sample_data",
    "matplotlib/mpl-data/fonts/afm",
    "matplotlib/mpl-data/fonts/pdfcorefonts",
    "matplotlib/mpl-data/images",
)


def _keep(entry):
    dest = entry[0].replace("\\", "/")
    return not dest.startswith(_MPL_STRIP_PREFIXES)


a.datas = [e for e in a.datas if _keep(e)]

pyz = PYZ(a.pure, cipher=block_cipher)

# ── Executable ─────────────────────────────────────────────────────────
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Diagrammer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # GUI app, no terminal window
    icon=WIN_ICON if IS_WIN else MAC_ICON,
)

# ── Collect into folder ───────────────────────────────────────────────
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Diagrammer",
)

# ── macOS .app bundle ─────────────────────────────────────────────────
if IS_MAC:
    app = BUNDLE(
        coll,
        name="Diagrammer.app",
        icon=MAC_ICON,
        bundle_identifier="com.diagrammer.app",
        info_plist={
            "CFBundleDisplayName": "Diagrammer",
            "CFBundleShortVersionString": APP_VERSION,
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "12.0",
        },
    )
